name: moneymanage

packages:
  - core/**
  - core_ui/**
  - data/**
  - domain/**
  - '*'

scripts:
  analyze:
      run: melos exec -- flutter analyze .
      description: Run `dart analyze` in all packages.