name: moneymanage
description: A Flutter money managing application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^5.2.4
  fluro: ^2.0.4
  json_annotation: ^4.7.0
  get: ^4.6.1
  dio: ^4.0.6
  rxdart: ^0.27.7
  provider: ^6.0.5
  get_it: ^7.2.0
  stack_trace: ^1.10.0
  flutter_ume: ^1.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  introduction_screen: ^3.1.1
  flutter_svg: ^1.1.6

  cupertino_icons: ^1.0.2

  core:
    path: core
  domain:
    path: domain
  data:
    path: data
  core_ui:
    path: core_ui
  authorization:
    path: features/authorization

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/resources/en.json
    - assets/resources/ru.json

  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/sf-ui/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/sf-ui/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/sf-ui/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/sf-ui/SFUIDisplay-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
