name: authorization
description: A new Flutter package project.
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  moneymanage:
    path: ../../

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: